### ISSUE TITLE
求职者-个人信息

### ISSUE THREAD

**Issue by joyongzhu** [LouPlus/jobplus7-1#28]
求职者登陆后配置个人信息
表单：姓名、邮箱、密码、手机号、工作年限、上传简历、提交button

**Comment by enjoyphen** [comment]
邮箱在注册的时候就已经确定了,这里再写邮箱的话,是修改邮箱吗?

**Comment by joyongzhu** [comment]
投递简历的邮箱并不一定是注册邮箱。
